# Backstabber Toolkit - Project Configuration
# Main configuration file for Backstabber Toolkit

# Application configuration
app:
  name: "Backstabber Toolkit"
  version: "1.0.0"
  author: "Esaú Aguilar"
  description: "Modular network pentesting tool with graphical interface"
  main_module: "main"
  gui_enabled: true

# Graphical user interface configuration
gui:
  window:
    title: "Backstabber Toolkit"
    width: 1200
    height: 800
    resizable: true
    icon: "assets/logoBT.png"
  
  tabs:
    - name: "Network Scanner"
      module: "gui.network_scanner_tab"
      enabled: true
    - name: "ARP Spoofing"
      module: "gui.arp_spoof_tab"
      enabled: true
    - name: "Packet Capture"
      module: "gui.packet_capture_tab"
      enabled: true

# Network configuration
network:
  default_interface: "eth0"
  scan_timeout: 5
  arp_timeout: 2
  max_threads: 50
  
  # Default IP ranges for scanning
  default_ranges:
    - "192.168.1.0/24"
    - "10.0.0.0/24"
    - "172.16.0.0/24"
  
  # Common ports for scanning
  common_ports:
    - 21    # FTP
    - 22    # SSH
    - 23    # Telnet
    - 25    # SMTP
    - 53    # DNS
    - 80    # HTTP
    - 110   # POP3
    - 143   # IMAP
    - 443   # HTTPS
    - 993   # IMAPS
    - 995   # POP3S

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_rotation: true
  max_file_size: "10MB"
  backup_count: 5
  
  # Specific log files
  files:
    arp_spoof_core: "src/logs/arp_spoof_core_log.txt"
    arp_spoof_gui: "src/logs/arp_spoof_gui_log.txt"
    network_scan: "src/logs/network_scan_log.txt"
    network_analysis: "src/logs/network_analysis_summary.txt"

# Security configuration
security:
  require_root: false
  allowed_interfaces: ["eth0", "wlan0", "en0", "en1"]
  max_scan_targets: 1000
  rate_limit: 100  # packets per second

# ARP Spoofing configuration
arp_spoof:
  default_gateway: "192.168.1.1"
  spoof_interval: 2  # seconds
  restore_on_exit: true
  monitor_mode: true

# Packet capture configuration
packet_capture:
  buffer_size: 65536
  promiscuous_mode: true
  timeout: 1000  # milliseconds
  filters:
    - "tcp"
    - "udp"
    - "arp"
    - "icmp"

# Development configuration
development:
  debug_mode: false
  verbose_logging: false
  auto_save_logs: true
  test_mode: false

# Dependencies configuration
dependencies:
  python_version: ">=3.8"
  required_packages:
    - "PyQt5>=5.15.9"
    - "scapy>=2.4.5"
    - "python3-nmap>=1.9.1"
    - "netifaces>=0.11.0"
    - "pyshark>=0.4.4"
    - "rich>=14.0.0"
    - "PyYAML>=6.0"
  
  optional_packages:
    - "wireshark"
    - "nmap"

# Paths configuration
paths:
  src: "src"
  logs: "src/logs"
  assets: "assets"
  config: "."
  temp: "/tmp/backstabber"
  output: "output"
